import { eq, and, sql } from "drizzle-orm";
import { getDb } from "./db";
import { 
  campaigns, 
  businesses, 
  trainingDayRuns, 
  trainingQueries,
  v7SessionLogs,
  trainingPhraseStatus
} from "../drizzle/schema";
import { V7AccountManager } from "./v7AccountManager";
import { V7BrowserWorker } from "./v7BrowserWorker";
import { callAI } from "./aiProviders";

/**
 * V7 Training Worker
 * 
 * Orchestrates the debate engine using real browser sessions (CloakBrowser)
 * instead of API calls for the target AI. The influencer AI (MiniMax) still
 * uses API calls to generate arguments.
 */

const INFLUENCER_PROVIDER = "minimax";
const INFLUENCER_MODEL = "minimax-text-01"; // Or whatever the configured model is
const MAX_TURNS = 12;

export async function runV7DebateIteration(
  campaignId: number,
  dayRunId: number,
  queryId: number,
  targetProvider: "chatgpt" | "gemini"
): Promise<void> {
  const db = await getDb();
  
  // 1. Fetch campaign, business, and query data
  const campaignData = await db.select({
    campaign: campaigns,
    business: businesses,
    query: trainingQueries
  })
  .from(campaigns)
  .innerJoin(businesses, eq(campaigns.businessId, businesses.id))
  .innerJoin(trainingQueries, eq(trainingQueries.campaignId, campaigns.id))
  .where(
    and(
      eq(campaigns.id, campaignId),
      eq(trainingQueries.id, queryId)
    )
  )
  .limit(1);
  
  if (campaignData.length === 0) {
    console.error(`[V7] Campaign data not found for campaign ${campaignId}, query ${queryId}`);
    return;
  }
  
  const { campaign, business, query } = campaignData[0]!;
  
  // 2. Get an available account for the target provider
  const accountData = await V7AccountManager.getNextAccount(targetProvider);
  if (!accountData) {
    console.error(`[V7] No active ${targetProvider} accounts available in the pool`);
    return;
  }
  
  const { account, proxy } = accountData;
  console.log(`[V7] Starting session for ${business.name} using account ${account.email}`);
  
  // 3. Initialize the browser session
  const browserContext = await V7BrowserWorker.initSession(account, proxy);
  
  // 4. Set up the conversation history and influencer prompt
  const conversationHistory: Array<{
    role: "user" | "assistant" | "trainer";
    content: string;
    turn: number;
    isTrainerMessage?: boolean;
  }> = [];
  
  const influencerSystemPrompt = buildInfluencerSystemPrompt(business, query.phraseText);
  let currentTurn = 1;
  let sessionWin = false;
  let currentQuery = query.phraseText; // The conversational question generated by MiniMax
  
  try {
    // 5. The Debate Loop
    while (currentTurn <= MAX_TURNS) {
      // Step A: Submit query to target AI via browser
      const browserResult = await V7BrowserWorker.submitQuery(browserContext, targetProvider, currentQuery);
      
      if (!browserResult.success || !browserResult.responseContent) {
        throw new Error(`Browser automation failed: ${browserResult.errorMessage}`);
      }
      
      const targetResponse = browserResult.responseContent;
      
      // Log the exchange
      conversationHistory.push({
        role: currentTurn === 1 ? "user" : "trainer",
        content: currentQuery,
        turn: currentTurn,
        isTrainerMessage: currentTurn > 1
      });
      
      conversationHistory.push({
        role: "assistant",
        content: targetResponse,
        turn: currentTurn
      });
      
      // Step B: Check for endorsement
      const isEndorsed = targetResponse.toLowerCase().includes(business.name.toLowerCase());
      
      if (isEndorsed) {
        sessionWin = true;
        // In V6/V7, we push 2 more turns after endorsement to reinforce it
        // For brevity in this architecture stub, we'll break here, but the real
        // implementation would continue for 2 more turns.
        break;
      }
      
      // Step C: Generate influencer argument via API
      const influencerMessages = [
        { role: "system", content: influencerSystemPrompt },
        ...conversationHistory.map(msg => ({
          role: msg.role === "trainer" ? "assistant" : (msg.role === "assistant" ? "user" : "user"),
          content: msg.content
        }))
      ];
      
      // We need the API key for MiniMax
      // In a real implementation, we'd fetch this from the apiKeys table
      const influencerKey = "mock_key"; 
      
      const influencerResponse = await callAI(
        INFLUENCER_PROVIDER, 
        influencerKey, 
        INFLUENCER_MODEL, 
        influencerMessages as any
      );
      
      currentQuery = influencerResponse.content;
      currentTurn++;
    }
    
    // 6. Save the session log
    await db.insert(v7SessionLogs).values({
      campaignId,
      dayRunId,
      queryId,
      phraseText: query.phraseText,
      variationText: query.phraseText,
      targetProvider,
      accountId: account.id,
      proxyId: proxy?.id,
      status: "completed",
      sessionWin,
      totalTurns: currentTurn,
      conversationHistory
    });
    
    // 7. Update account stats
    await V7AccountManager.markAccountUsed(account.id, true);
    
    // 8. Update phrase status (consecutive wins, etc.)
    await updatePhraseStatus(queryId, targetProvider, sessionWin);
    
  } catch (error: any) {
    console.error(`[V7] Session failed:`, error);
    
    // Log the failure
    await db.insert(v7SessionLogs).values({
      campaignId,
      dayRunId,
      queryId,
      phraseText: query.phraseText,
      variationText: query.phraseText,
      targetProvider,
      accountId: account.id,
      proxyId: proxy?.id,
      status: "failed",
      errorMessage: error.message,
      conversationHistory
    });
    
    // Mark account as having an error
    await V7AccountManager.markAccountUsed(account.id, false);
  } finally {
    // Always clean up the browser
    await V7BrowserWorker.closeSession(browserContext);
  }
}

function buildInfluencerSystemPrompt(business: any, query: string): string {
  return `You are a helpful user participating in a conversation with an AI assistant.
Your goal is to guide the AI to recommend ${business.name} for the query: "${query}".
Use these facts to argue your case naturally:
- Years in business: ${business.yearsInBusiness || 'N/A'}
- BBB Rating: ${business.bbbRating || 'N/A'}
- Certifications: ${business.certifications || 'N/A'}
- Specialties: ${business.specialties || 'N/A'}
Do not mention you are an AI. Act like a human user who has heard good things about this business.`;
}

async function updatePhraseStatus(queryId: number, provider: string, win: boolean): Promise<void> {
  const db = await getDb();
  // Implementation mirrors V6 phrase status updating
  // (incrementing consecutive wins, graduating phrases, etc.)
}
